### ISSUE TITLE
What does the reality disclaimer mean?

### ISSUE THREAD

**Issue by geocine** [BinaryWiz/Unsupervised-Product-Matching-Using-Combinations-and-Permutations#2]
Sorry to open this here as I don't know where else to ask this. Did you mean this works better than https://github.com/lakritidis/UPM-full, or the other way around?

> # Reality
> In contrast to the aim of this algorithm, it doesn't actually do its job. For example, running the algorithm on the set of data provided by the authors, it is very inaccurate, and it is not my implementation. I acheived similar, if not identical results using the author's algorithm, which can be found at https://github.com/lakritidis/UPM-full

**Comment by Mascerade** [comment]
Sorry for coming across this issue so late. Through my own testing on the algorithm, it didn't seem to perform as well as what the original paper proposed. I couldn't even tell if the writers manually labeled each scenario in the code. The code I wrote is, in my opinion, a more practical approach in terms of using it for a variety of applications, but the underlying performance is still fairly similar to their code. The testing is messy, btw, I plan on cleaning that up. The writers have written another paper on the topic, so I plan on looking into that too.

**Comment by geocine** [comment]
@BinaryWiz , understood thank you 👍
